### ISSUE TITLE
It could not install `instadm` with pip

### ISSUE THREAD

**Issue by anjandash** [CamTosh/instagram-bot-dm#3]
$ pip3 install instadm
ERROR: Could not find a version that satisfies the requirement instadm (from versions: none)
ERROR: No matching distribution found for instadm

### 

$ python3 --version
Python 3.7.7

**Comment by reubence** [comment]
Hi! InstaDM was a class created within the file InstaDM.py. In order to get it working you will need to wither fork this repo and import the file locally or you could do what i did and copy paste the code to make it work locally. It isn't available as a pypi package so you cannot install it using pip. 

Hope that helps!

**Comment by dvershinin** [comment]
Why not make a pip package? :)

**Comment by CamTosh** [comment]
@dvershinin I don't have the time

**Comment by dvershinin** [comment]
@CamTosh please see https://github.com/CamTosh/instagram-bot-dm/pull/33
